config/routes.rb
Stackoverflow::Application.routes.draw do
  
  
  devise_for :users
  
=begin
  resources :questions
  resources :answers, only: [:edit, :create, :update, :destroy] 
  resources :comments, only: [:edit, :create, :update, :destroy]
=end

  resources :questions do
    resources :answers , only: [:edit, :create, :update, :destroy]
  end
  resources :comments, only: [:edit, :create, :update, :destroy]
  

  root to: 'questions#index'
  

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, [Question, Answer, Comment]

      can [:update, :destroy], Question do |question|
        user.id == question.user_id 
      end
      
      can [:update, :destroy], Answer do |answer|
        user.id == answer.user_id 
      end

      can [:update, :destroy], Comment do |comment|
        user.id == comment.user_id 
      end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	has_many   :comments, as: :commentable, dependent: :destroy
	belongs_to :question
	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: :true
	belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many   :answers, dependent: :destroy
	has_many   :comments, as: :commentable, dependent: :destroy
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
	has_many :questions, dependent: :destroy
	has_many :answers, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :question
  load_and_authorize_resource through: :question

  # GET /answers/1/edit
  def edit
    respond_to do |format|
      format.json { redirect_to root_path, notice: t(:json_error) }
      format.html
    end
  end
  
  # POST /answers
  def create
    @answer.user_id = current_user.id
    
    respond_to do |format|
      if @answer.save
        format.html { redirect_to request.referer, notice: t(:answer_created)  }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /answers/1
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer.question, notice: t(:answer_updated) }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  
  # DELETE /answers/1
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @answer.question, notice: t(:answer_deleted)  }
    end
  end
  
  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:detail, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale
 
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /comments/1/edit
  def edit
    respond_to do |format|
      format.json { redirect_to root_path, notice: t(:json_error) }
      format.html { }
    end
  end
  

  # POST /comments
  def create
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to request.referer, notice: t(:comment_created)  }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /comments/1
  def update
    commentable = get_redirect_route

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to commentable, notice: t(:comment_updated) }
      else
        format.html { render action: 'edit' }
      end
    end
  end


  # DELETE /comments/1
  def destroy
    commentable = get_redirect_route
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to commentable, notice: t(:comment_deleted)  }
    end
  end

  private
    def get_redirect_route
      commentable = @comment.commentable
    
      if @comment.commentable_type == 'Answer'
        commentable = commentable.question
      end
      return commentable
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:detail, :commentable_id, :commentable_type)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  # GET /questions
  def index
    @questions = @questions.page(params[:page]).per_page(5)
  end

  # GET /questions/1
  def show
    respond_to do |format|
      format.json { redirect_to root_path, notice: t(:json_error) }
      format.html { }
    end
    @comments = @question.comments.paginate(page: params[:page], per_page: 2)
    @answers  = @question.answers
    @comment  = @question.comments.build
    #@answer  = @question.answers.build 
  end

  # GET /questions/new
  def new
    respond_to do |format|
      format.json { redirect_to root_path, notice: t(:json_error) }
      format.html { @question = current_user.questions.build }
    end
  end

  # GET /questions/1/edit
  def edit
    respond_to do |format|
      format.json { redirect_to root_path, notice: t(:json_error) }
      format.html { }
    end
  end

  # POST /questions
  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: t(:question_created) }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /questions/1
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: t(:question_updated) }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: t(:question_deleted)  }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :description)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<% if can? :create, answer %>
  
    <h2> Post Answer </h2>

    <%= form_for ([answer.question, answer]) do |f| %>
      <% if answer.errors.any? %>
        <%= render 'shared/error_explanation', obj: answer  %>
      <% end %>

      <div class="field">
        <%= f.text_area :detail, placeholder: "Enter your answer here"  %>
      </div>
      
      <%= f.hidden_field :question_id %>
      <div class="actions">
        <%= f.submit %>
      </div>

    <% end %>
 
<% end %>

app/views/answers/_show.html.erb
<% comments = answer.comments.paginate(page: params[:page], per_page: 2) %>
<h3> Answer </h3>

<div class="answer">
  <p>
    <%= answer.detail %>
    <% if can? :update, answer %> 
  	  	<%= link_to 'Edit', edit_question_answer_path(answer.question_id, answer) %>
    <% end %>

    <% if can? :destroy, answer %>
  	  	<%= link_to 'Delete', [answer.question, answer], method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    
    <strong> -- <%= answer.user.email %> -- </strong>
  </p>
</div>

<div class="comments" >
  <b> Comments </b>
  <%= render partial: 'comments/show', collection: comments, as: :comment  %>
  <%= will_paginate comments %>

  <% comment = answer.comments.build %>
  <%= render 'comments/form', comment: comment  %>
</div>

app/views/answers/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing answer</h1>
<%= render 'form', answer: @answer %>
<%= link_to 'Back', @answer.question %>

app/views/comments/_form.html.erb
<% if can? :create, comment %>
  <div>
    <strong> Post Comment </strong>

    <%= form_for(comment) do |f| %>
      <% if comment.errors.any? %>
        <%= render 'shared/error_explanation', obj: comment  %>
      <% end %>

      <div class="field">
        <br />
        <%= f.text_area :detail, placeholder: "Enter your comment here" %>
      </div>

      <%= f.hidden_field :commentable_id %>
      <%= f.hidden_field :commentable_type %>
      <br />

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>   
<% end %>
  

app/views/comments/_show.html.erb
<p>
  
  <%= comment.detail %>
  <% if can? :update, comment %>
	  	<%= link_to 'Edit', edit_comment_path(comment) %>
  <% end %>

  <% if can? :destroy, comment %>
	  	<%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
	
  <strong> -- <%= comment.user.email %> -- </strong> 
</p>

app/views/comments/edit.html.erb
<p id="notice"><%= notice %></p>
<h1>Editing comment</h1>
<%= render 'form', comment: @comment  %>
<%= link_to 'Back', request.referer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title> Stack overflow</title>
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>

	<body class="<%= controller.controller_name %>">

		<div id="banner">
			<%= image_tag "logo.png" %>
			<%= @page_title || "Stack overflow" %>
			<% if user_signed_in? %>
				<div id="sign_in"> 
					<p> <%= link_to "log out", destroy_user_session_path, method: 'delete' %> </p>
				</div>
			<% else %>
				<div id="sign_in"> 
					<p> <%= link_to "log in", new_user_session_path %> </p>
				</div>
			<% end %>
		</div>

		<div id="columns">
			<div id="side">
				<ul>
					<li><a href= <%= root_path %> >Home</a></li>
					<li><a href= <%= root_path %> >Questions</a></li>
				</ul>
			</div>
			<div id="main">
				<%= yield %>
			</div>
		</div>
		
	</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <%= render 'shared/error_explanation', obj: @question  %>
  <% end %>

  <div class="field">
    <%= f.label :title %> <br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %> <br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>
<%= render 'form' %>
<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td>  <b><%= question.title %> </b></td>
        <td><%= link_to 'Show', question %></td>
        <% if can? :update, question %>
          <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <% end %>
        <% if can? :destroy, question %>  
            <td><%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <tr> 
        <td> <hr> </td> 
        <td> <hr> </td>
        <td> <hr> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @questions %>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>
<%= render 'form' %>
<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <h1>
  	<strong>Title:</strong>
  	<%= @question.title %>
  </h1>
</p>

<p>
  <div class="question-description"> <%= @question.description %> </div>
</p>

<% if can? :update, @question %>
		<%= link_to 'Edit', edit_question_path(@question) %> 
<% end %>

<% if can? :create, @question %>
		<%= link_to 'New Question', new_question_path %>
<% end %>

<div class="comments" >
	<h2> Comments </h2>
	<%= render partial: 'comments/show', collection: @comments, as: :comment  %>
  <%= will_paginate @comments %>

	<br />
  <% comment = @question.comments.build %>
  <%= render 'comments/form', comment: comment %>
</div>

<br />
<div class="answers">
	<h2> Answers </h2>
		<%= render partial: 'answers/show', collection: @answers, as: :answer %>
	<br />
	<% answer  = @question.answers.build %>
	<div class="answer-form">
		<%= render 'answers/form', answer: answer  %>
	</div>

</div>

app/views/shared/_error_explanation.html.erb
<div id="error-explanation">
  <h2><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name %> from being saved:</h2>

  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>